<?php
// +----------------------------------------------------------------------
// | 模板文案翻译表 —— 从 beauts_app/locale/zh-Hans.json 抄过来
// |   后续做多语言时再补 zh-Hant / en / ja / th
// +----------------------------------------------------------------------
return [
    'zh-Hans' => [
        'projectDetails.Stopplay'              => '退出播放',
        'projectDetails.Empty'                 => '空空如也',
        'projectDetails.Nomore'                => '没有更多了',
        'hospitalDetails.tabs.Priceitem'       => '价格明细',
        'hospitalDetails.tabs.news'            => '透明',
        'hospitalDetails.tabs.Eventitem'       => '活动明细',
        'hospitalDetails.tabs.month'           => '5月特惠',
        'hospitalDetails.Floor'                => '层',
        'hospitalDetails.Pointgift'            => '积分好礼',
        'hospitalDetails.Userfeedback'         => '用户反馈',
        'hospitalDetails.Moreinstitution'      => '更多机构',
        'hospitalDetails.Commercialcircle'     => '所属商圈',
        'hospitalDetails.Floorarea'            => '机构面积',
        'hospitalDetails.Floorlayer'           => '机构层数',
        'hospitalDetails.Floorunit'            => '层',
        'hospitalDetails.Institutionallevel'   => '机构级别',
        'hospitalDetails.Deannum'              => '代表院长数',
        'hospitalDetails.Specialtydeannum'     => '专科院长数',
        'hospitalDetails.Assistantnum'         => '助理数',
        'hospitalDetails.Institutionsevice'    => '机构服务',
        'hospitalDetails.Certifications'       => '机构资质',
        'hospitalDetails.Transportation'       => '机构交通',
        'doctorDetails.BusinessHours'          => '营业时间',
        'projectDetails.Iteminstitution'       => '项目机构',
        'projectDetails.Itemintroduction'      => '项目介绍',
        'projectDetails.Itemrecommend'         => '推荐项目',
        'index.common.AlreadyBooked'           => '已预约',
        'index.common.SpecializesIn'           => '擅长',
        'search.resultsFor'                    => '搜索',
        'search.foundCount'                    => '共',
        'search.itemsUnit'                     => '条结果',
        'doctorDetails.YearsOld'               => '岁',
        'doctorDetails.YearsOfExperience'      => '从业时间',
        'doctorDetails.Position'               => '职位',
        'doctorDetails.SurgicalStyle'          => '手术风格',
        'doctorDetails.UniversityTeaching'     => '大学执教',
        'doctorDetails.PracticeInChina'        => '中国出诊',
        'doctorDetails.AffiliatedInstitution'  => '执业机构',
        'doctorDetails.SpecializesIn'          => '医生擅长',
        'doctorDetails.DeansProfile'           => '院长简介',
        'doctorDetails.SignaturePrograms'      => '特色项目',
        'index.common.yes'                     => '是',
        'index.common.no'                     => '否',
        'index.common.FeaturedCases'           => '精选案例',
        'index.common.ViewAll'                 => '查看全部',
        'index.common.BookingResponseTime'     => '预约响应时长',
        'index.common.Hour'                    => '小时',
        'index.common.ConsultationFee'         => '面诊费',
        'index.common.Comparison'              => '对比',
        'index.common.Favorites'               => '收藏',
        'index.common.CustomerService'         => '客服',
        'index.common.BookNow'                 => '预约面诊',
        'index.common.point'                   => '积分',
        'index.common.AlreadyRedeemed'         => '已兑',
        'index.common.chatNow'                 => '咨询一下',
        'point.PointsExchange'                 => '积分兑换',
        'point.Orderpoint'                     => '下单送积分',
        'point.Empty'                          => '暂无数据',
        // 首页
        'index.search.placeholder'             => '搜索机构、项目、医生',
        'index.tabs.hospital'                  => '甄选机构',
        'index.tabs.project'                   => '热推项目',
        'index.tabs.doctor'                    => '口碑院长',
        'index.tabs.point'                     => '积分商城',
        'index.tabs.all'                       => '全部',
        'seo.home.title'                       => '韩国医美预约平台',
        'seo.home.description'                 => 'BeautsGO 中韩同价、价格透明的韩国医美预约平台，覆盖整形、皮肤、抗衰等全品类项目，连接 900+ 顶尖机构与求美者。',
        'tabbar.home'                          => '首页',
        'tabbar.hospital'                      => '机构',
        'tabbar.doctor'                        => '医生',
        'tabbar.me'                            => '我的',
        'filter.allArea'                       => '全部商圈',
        'filter.more'                          => '更多筛选',
        'filter.feature'                       => '医院特色',
        'filter.specialty'                     => '擅长项目',
        'filter.category'                      => '项目分类',
        'filter.hotProject'                    => '热门项目',
        'filter.serviceLang'                   => '服务语种',
        'filter.btnLabel'                      => '筛选',
        'filter.lang.zh'                       => '中文',
        'filter.lang.ja'                       => '日语',
        'filter.lang.en'                       => '英语',
        'filter.lang.zhtw'                     => '繁中',
        'filter.reset'                         => '重置',
        'filter.apply'                         => '确定',
        'pagination.prev'                      => '上一页',
        'pagination.next'                      => '下一页',
        'hospital.samePrice'                   => '中韩同价',
        'hospital.doctorsUnit'                 => '位医生',
    ],

    // 其他语言暂时回落到 zh-Hans，后续填
    'zh-Hant' => [],
    'en'      => [],
    'ja'      => [],
    'th'      => [],
];
